### ISSUE TITLE
Issue with opening picker after snippet redraw

### ISSUE THREAD

**Issue by juniwalk** [migliori/universal-icon-picker#10]
I am using your picker with Nette Framework (php) and Naja.js (js) which uses "snippets" as blocks of html to be updated after ajax request.

After update of the snippet with picker in it, it would not reopen, I had to add to add `onBeforeOpen` listener to remove `uip-close` class.

```javascript
$('input.icon-picker').each(function() {
	let preview = $(this).parents('.input-group').find('.icon-preview i');
	let target = $(this).attr('id');

	let iconPicker = new UniversalIconPicker('#'+target, {
		iconLibraries: ['font-awesome.min.json'],

		onBeforeOpen: function() {
			$('#uip-modal-'+target).removeClass('uip-close');
		},
	
		onSelect: function(info) {
			$(preview).attr('class', info.iconClass).addClass('fa-fw');
			$('#'+target).val(info.iconClass);
		}
	});

	$(preview).attr('class', $(this).val()).addClass('fa-fw');
});
```

Edit: This code gets called on load and after snippet update so picker should be reinitialized.

**Comment by juniwalk** [comment]
The fact that I have to do in `onBeforeOpen` what should be done in `open` method by the iconpicker is not a problem?

**Comment by migliori** [comment]
Indeed I don't know exactly the way you load your page, snippet and ajax data.
Adding `$('#uip-modal-'+target).removeClass('uip-close');` somewhere in the plugin CORE code might solve the issue, but I can't reproduce the case easily.

**Comment by juniwalk** [comment]
Well there is this code in `open` method that I think handles this:
```javascript
                } else {
                    //Icon library open if dom element exist
                    this.universalDomEle.classList.remove('uip-close');
                    this.universalDomEle.classList.add('uip-open');
                }
```

Which means the issue must be there? My javascript knowledge is very limited, I might try to fix it however I don't know if I won't break something else.

**Comment by migliori** [comment]
Yes, that's the question. I don't want to break anything, so I'd need to be able to reproduce your issue.

If you can provide me a simple test file, without using any framework or external tool then I'll work on it.
