### ISSUE TITLE
Mobile friendly

### ISSUE THREAD

**Issue by MikeAlhayek** [migliori/universal-icon-picker#18]
First of all, thank you for this library. 

Have you tried viewing it on a mobile devise? The icons are not rendering nicely. 

Also, is there an option to not show the font name as filter on the left? I want it to open as a small/mid size pop up not as a full screen.

**Comment by migliori** [comment]
Hi,

Thanks for reporting this, I'll make it responsive and add the ability to collapse the left sidebar as soon as possible

**Comment by migliori** [comment]
Done - the sidebar doesn't collapse but is visible in all screens resolutions. The icon grid has been reworked for responsive display.
