### ISSUE TITLE
License inconsitency

### ISSUE THREAD

**Issue by Ash-Crow** [migliori/universal-icon-picker#22]
Hi,

The [README.md](https://github.com/migliori/universal-icon-picker/blob/main/README.md) file says that the tool is under MIT license, but the [package.json](https://github.com/migliori/universal-icon-picker/blob/main/package.json) file says "GPL-3.0-or-later"

Can you please clarify which it is?

I was about to use your lib for a MIT-licensed tool, but the virality of the GPL would prevent that.

**Comment by migliori** [comment]
Hi,

Sorry for the confusion. I definitely set the license to MIT.
