### ISSUE TITLE
Missing type="button" on buttons

### ISSUE THREAD

**Issue by juniwalk** [migliori/universal-icon-picker#27]
Right now when I use new parentElement to insert icon picker into form modal, inserting icon submits form. To fix this I need `type="button"` on buttons inside the picker.

See #26 for parentElement issue.

**Comment by migliori** [comment]
I added the type="button" on buttons inside the picker.

**Comment by juniwalk** [comment]
Thank you. All works now as it should.

**Comment by migliori** [comment]
Nice!
