### ISSUE TITLE
Custom Library Creation

### ISSUE THREAD

**Issue by cmlnrowan** [migliori/universal-icon-picker#4]
Spectacular work!  Simple and elegant.  

I am looking for an icon picker for a custom collection of svg's.

Is it possible to accomplish this with your package?

**Comment by migliori** [comment]
Thanks for your comment.

Yes, it'll be easy, here's how I'd proceed:

1. Go to [Icomoon](https://icomoon.io/) and open the app
2. Import your svg icons into the app and select them
3. click the preferences and choose your prefered font name and prefix
4. generate your icon font
5. Add your font files into universal-icon-picker/assets/fonts/
6. Add your icons stylesheet into universal-icon-picker/assets/stylesheets/
7. Create a new json file for your font in universal-icon-picker/assets/icons-libraries/
(Use the same structure as in the thoers json files in this folder)

I should add a tiny documentation for this, will do it as soon as I can free some time.
