### ISSUE TITLE
Note down version on icon set json files

### ISSUE THREAD

**Issue by fsbraun** [migliori/universal-icon-picker#7]
@migliori Still love your picker! Here's one thing that came to my mind:

To track down which version of the icon set belongs to I suggest to add a `version` property (string) which notes down the version of the icon set was used when generating the json file.

This needs not to be used by the picker but helps humans to keep track of the supported icon sets.

**Comment by migliori** [comment]
That's a good idea. I added the versions to the JSON icon files.

**Comment by fsbraun** [comment]
One more question: How do you create the JSON files? I saw the tool for FontAwesome. Say, I'd like to contribute an update on some library (bootstrap, e.g.). How can I create the JSON file?

**Comment by migliori** [comment]
Hi Fabian,

I had to build the tool for FontAwesome, but for others libraries I did 
it as I could, according to the data I could retrieve: copied/pasted the 
lists of icons in vs-code then formatted them.

Gilles Migliori - Web developer
https://codecanyon.net/user/migli/portfoliohttps://www.miglisoft.com+33 9 54 71 79 93
+33 6 99 07 24 43


------ Message d'origine ------
De "Fabian Braun" ***@***.***>
À "migliori/universal-icon-picker" 
***@***.***>
Cc "Gilles Migliori" ***@***.***>; "State change" 
***@***.***>
Date 31/03/2023 09:49:57
Objet Re: [migliori/universal-icon-picker] Note down version on icon set 
json files (Issue #7)
