### ISSUE TITLE
Asset manager does not work with "iconPickerUrl"

### ISSUE THREAD

**Issue by juniwalk** [migliori/universal-icon-picker#8]
Hello,
I just implemented your icon picker which just saved me around 250MB of disk space compared to old one, thanks! :D

I wanted to ask, is the use of "iconPickerUrl" necessary? I have asset manager that moves assets I want to include in my page outside their original folder and that of course breaks this.

If there would be an option to set custom paths, or manually load things and icon picker would still work that would be great.

**Comment by migliori** [comment]
Hello,

The iconPickerUrl uses [document.currentScript.src](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) to get the URL of the iconpicker (assets/js/universal-icon-picker.min.js)

It allows to locate the assets folder URL then load the dependencies (iconpîcker CSS, font files, images) without hassle.
You just need to keep the structure of the assets folder and its contents, which I think is good practice.

If your dependency manager forces you to move the dependencies of a plugin into other folders, you should explain to him that this is not a good idea at all.

**Comment by juniwalk** [comment]
Haven't had issue till now to be honest, but good thing it's my work so I can change it. Thanks.
