### ISSUE TITLE
Modal templates

### ISSUE THREAD

**Issue by juniwalk** [migliori/universal-icon-picker#9]
Is there easy way to add template functionality? I'd like to switch to bootstrap modal as it has much better responsibility and wit would work with my dark mode out of the box.

**Comment by migliori** [comment]
The Iconpicker modal has a specific structure with ids, classes, sidebar, tabs, preview area, ...

If you change the structure it'll lead to unexpected behaviours. And I don't want to overcharge the code with Bootstrap specific conditions.

The most reasonable solution would be in my opinion to edit the CSS to match your dark mode,
or fork the iconpicker and write your own version specificly for use with Bootstrap.

**Comment by juniwalk** [comment]
I understand, however your modal structure as is is very similar to bootstraps modals, might be enough just to add classes for bootstrap.

If you'd be ok with that I might try it and send PR.

**Comment by migliori** [comment]
That's perfect, thanks.

**Comment by fsbraun** [comment]
I use custom css to also have a dark mode. This uses the `loadCustomCss` option.
